// functions/init.js
// 访问 /init 触发数据初始化（部署后只需访问一次）

// ======================= 原有 100 条数据 =======================
const SEED_DATA = [
  // 系列 A：不玩手机的1000件小事
  // 系列 A：不玩手机的1000件小事
  { series_id: 'A', title: '去天台听一次邻居家的吵架声', desc: '感受人间烟火', mood: '治愈', cost: '10分钟' },
  { series_id: 'A', title: '用树叶拼一幅画', desc: '自然创作', mood: '治愈', cost: '20分钟' },
  { series_id: 'A', title: '写一封手写信给老朋友', desc: '重温旧情', mood: '温情', cost: '30分钟' },
  { series_id: 'A', title: '观察蚂蚁搬家', desc: '微观世界', mood: '好奇', cost: '15分钟' },
  { series_id: 'A', title: '做一次家庭断舍离', desc: '极简生活', mood: '清爽', cost: '1小时' },
  { series_id: 'A', title: '去公园喂鸽子', desc: '城市野趣', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '学折一只千纸鹤', desc: '手工时光', mood: '专注', cost: '5分钟' },
  { series_id: 'A', title: '看一场日出', desc: '早起挑战', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '整理手机相册', desc: '回忆杀', mood: '怀旧', cost: '40分钟' },
  { series_id: 'A', title: '给自己做一顿早餐', desc: '认真生活', mood: '温暖', cost: '20分钟' },
  { series_id: 'A', title: '做瑜伽、普拉提、拉伸', desc: '放松身心，提升柔韧性', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '在家跳绳健身', desc: '高效燃脂，提高心肺功能', mood: '充满活力', cost: '15分钟' },
  { series_id: 'A', title: '跑步（晨跑、夜跑）', desc: '呼吸新鲜空气，保持清醒', mood: '充满活力', cost: '30分钟' },
  { series_id: 'A', title: '散步、快走、公园漫步', desc: '放慢脚步，感受身边风景', mood: '放松', cost: '1小时' },
  { series_id: 'A', title: '爬山、徒步', desc: '亲近自然，挑战身体极限', mood: '充实', cost: '半天' },
  { series_id: 'A', title: '学习太极、八段锦、拍八虚', desc: '修身养性，强身健体', mood: '宁静', cost: '30分钟' },
  { series_id: 'A', title: '正念呼吸、练习瑜伽', desc: '专注当下，缓解焦虑', mood: '宁静', cost: '20分钟' },
  { series_id: 'A', title: '打篮球、羽毛球、乒乓球', desc: '挥洒汗水，享受竞技乐趣', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '跳绳、踢毽子', desc: '唤醒童年记忆，活动筋骨', mood: '开心', cost: '20分钟' },
  { series_id: 'A', title: '溜冰（户外、动感单车）', desc: '感受速度与激情', mood: '充满活力', cost: '1小时' },
  { series_id: 'A', title: '游泳（室内、户外）', desc: '全身运动，清凉解压', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '出游（室内、户外）', desc: '换个环境，换个心情', mood: '开心', cost: '半天' },
  { series_id: 'A', title: '冥想、放空、独处', desc: '给自己一个静下来的机会', mood: '宁静', cost: '15分钟' },
  { series_id: 'A', title: '跑步机跑步', desc: '不受天气影响，随心运动', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '俯卧撑、仰卧起坐', desc: '随时随地，增强核心力量', mood: '充实', cost: '15分钟' },
  { series_id: 'A', title: '自制腌菜、泡菜', desc: '体验动手的乐趣与成就感', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '咖啡拉花、茶艺、煮果茶', desc: '享受慢生活，培养耐心', mood: '治愈', cost: '40分钟' },
  { series_id: 'A', title: '发呆、睡个懒觉', desc: '放松大脑，给身体充电', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: 'DIY手机壳、冰箱贴', desc: '发挥创意，独一无二的专属物品', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '整理照片、制作相册', desc: '重温美好回忆，整理心情', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '清洁、保养或修理小家电', desc: '让生活更井井有条', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '熨烫衣服、补衣服', desc: '整理仪表，提升生活质感', mood: '平静', cost: '1小时' },
  { series_id: 'A', title: '涂色书、数字油画', desc: '沉浸色彩世界，释放压力', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '玩粘土、石塑粘土、轻粘土', desc: '捏出喜欢的小物件', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '改造奶茶杯子做手工', desc: '变废为宝，环保又有趣', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '画画（素描水彩油画）', desc: '用画笔表达内心世界', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '写诗、创作小说、写日记', desc: '记录思绪，与自己对话', mood: '宁静', cost: '1小时' },
  { series_id: 'A', title: '学乐器（吉他/尤克里里）', desc: '培养音乐细胞，陶冶情操', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '练字（硬笔、毛笔）', desc: '静心养气，一手好字', mood: '宁静', cost: '40分钟' },
  { series_id: 'A', title: '学编程、设计软件', desc: '掌握新技能，提升竞争力', mood: '专注', cost: '2小时' },
  { series_id: 'A', title: '读外语、新闻', desc: '拓展视野，紧跟时事', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '学Excel、PPT办公技能', desc: '提升工作效率，职场加分', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '学心理学、哲学', desc: '深度思考，认识自我', mood: '宁静', cost: '2小时' },
  { series_id: 'A', title: '学摄影技巧、剪辑软件', desc: '用镜头记录生活美好', mood: '充实', cost: '2小时' },
  { series_id: 'A', title: '看纪录片、TED演讲', desc: '获取知识，提升思维', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '学理财知识', desc: '合理规划，财富增值', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '和家人/爱人/朋友聊天、打电话', desc: '联络感情，感受温暖', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '逛花鸟市场', desc: '赏花逗鸟，体验生活情趣', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '去做按摩或护理', desc: '放松肌肉，关爱自己的身体', mood: '放松', cost: '1小时' },
  { series_id: 'A', title: '做志愿者', desc: '帮助他人，收获精神满足', mood: '充实', cost: '半天' },
  { series_id: 'A', title: '参观博物馆、艺术展', desc: '接受文化熏陶，提升审美', mood: '充实', cost: '半天' },
  { series_id: 'A', title: '逛街、跑步机、逛公园', desc: '边逛边玩，放松身心', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '逛公园、看花草树木', desc: '感受自然气息，治愈心灵', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '上团购平台的9.9元体验课', desc: '低成本尝试新事物', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '夜晚看星星、白天看云朵', desc: '抬头看天，感受宇宙浪漫', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '雨中打伞散步、踩水坑', desc: '找回童心，感受雨天的浪漫', mood: '开心', cost: '30分钟' },
  { series_id: 'A', title: '给自己拍漂亮的写真', desc: '记录当下最美的自己', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '去乡下看麦田、踩大地', desc: '接地气，感受田园风光', mood: '治愈', cost: '半天' },
  { series_id: 'A', title: '去海边看海、捡贝壳', desc: '听海浪声，放空自己', mood: '治愈', cost: '半天' },
  { series_id: 'A', title: '去公园野餐', desc: '享受阳光、美食与微风', mood: '开心', cost: '半天' },
  { series_id: 'A', title: '去听音乐会、看livehouse', desc: '沉浸在音乐中尽情摇摆', mood: '充满活力', cost: '夜晚' },
  { series_id: 'A', title: '逛夜市或夜场', desc: '感受城市的烟火气', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '逛农贸市场', desc: '感受生活气息，采购新鲜食材', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '参加社区夜校', desc: '结交新朋友，学习新知识', mood: '充实', cost: '2小时' },
  { series_id: 'A', title: '无目的地散步、坐公交车', desc: '漫无目的，享受城市漫游', mood: '放松', cost: '1小时' },
  { series_id: 'A', title: '学用手机拍摄电影感vlog', desc: '记录生活，提升审美', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '学做三分钟零失败快手家常菜', desc: '提升厨艺，照顾好自己的胃', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '通勤时听知识型播客', desc: '利用碎片化时间自我提升', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '看TED学高效沟通表达', desc: '提升表达能力，拓宽思维', mood: '专注', cost: '20分钟' },
  { series_id: 'A', title: '掌握常见食材的保鲜技巧', desc: '减少浪费，生活更从容', mood: '充实', cost: '20分钟' },
  { series_id: 'A', title: '掌握海姆立克急救法', desc: '关键时刻能救命', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '学化十分钟通勤快速妆', desc: '提升自信，开启美好一天', mood: '开心', cost: '10分钟' },
  { series_id: 'A', title: '每天背五个实用英语口语', desc: '日积月累，提升外语水平', mood: '专注', cost: '15分钟' },
  { series_id: 'A', title: '追纪录片学习世界地理', desc: '足不出户，看遍世界', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '掌握基础手语日常对话', desc: '多一种沟通方式，关爱他人', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '拆解漫画分镜构图技巧', desc: '提升审美与画面叙事能力', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '练习写出漂亮个人签名', desc: '提升个人形象与仪式感', mood: '开心', cost: '20分钟' },
  { series_id: 'A', title: '创建专注学习英文歌单', desc: '在音乐中学习，事半功倍', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '用Excel制作动态收表', desc: '掌握实用技能，高效管理', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '搞懂当地医保报销比例规则', desc: '了解政策，保障自身权益', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '定投指数基金练习理财', desc: '培养财商，规划未来', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '给朋友圈趣味Q版头像', desc: '展现个性，增加社交趣味', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '学用思维导图整理读书笔记', desc: '梳理逻辑，加深记忆', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '学习记账分析月度消费', desc: '理性消费，掌控财务状况', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '带旧包回收变卖钱买新书', desc: '断舍离，换回知识财富', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '练习拍摄并剪辑短视频', desc: '掌握新时代的内容创作技能', mood: '充实', cost: '2小时' },
  { series_id: 'A', title: '学习弹唱最爱歌的吉他版', desc: '用音乐表达情感，陶冶情操', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '学习制作简单动画表情包', desc: '创意表达，聊天更有趣', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '练习清晰有力的说话发音', desc: '提升气场，增强自信', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '设计一周营养早餐食谱', desc: '健康饮食，活力满满', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '速读一本书抓核心观点', desc: '高效获取知识，拓宽认知', mood: '专注', cost: '1小时' },
  { series_id: 'A', title: '用地图规划最优晨跑路线', desc: '安全高效，享受晨跑', mood: '充实', cost: '20分钟' },
  { series_id: 'A', title: '冥想五分钟清空大脑杂念', desc: '减压放松，找回专注', mood: '治愈', cost: '5分钟' },
  { series_id: 'A', title: '旧T恤改造环保购物袋', desc: '环保又有趣的DIY体验', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '爱回收旧包换钱学记账', desc: '循环利用，合理理财', mood: '充实', cost: '30分钟' },
  { series_id: 'A', title: '把多肉养出肥厚饱满状态', desc: '体验植物生长的治愈力', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '对着镜子练习即兴演讲', desc: '克服紧张，提升表达能力', mood: '专注', cost: '20分钟' },
  { series_id: 'A', title: '学简谱弹奏电子琴小曲', desc: '简单易学，感受音乐魅力', mood: '开心', cost: '40分钟' },
  { series_id: 'A', title: '学修图软件P出复古胶片', desc: '提升审美，让照片更高级', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '列每周可完成计划清单', desc: '时间管理，提升效率', mood: '专注', cost: '15分钟' },
  { series_id: 'A', title: '每天练凯格尔预防漏尿', desc: '关爱自身健康，受益终身', mood: '专注', cost: '10分钟' },
  { series_id: 'A', title: '看云层预判当日天气', desc: '亲近自然，增加生活常识', mood: '宁静', cost: '10分钟' },
  { series_id: 'A', title: '用康奈尔笔记法高效听课', desc: '提升学习效率，整合知识', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '读心理学书改善人际关系', desc: '读懂他人，也读懂自己', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '学用AI工具提升效率', desc: '拥抱新技术，释放生产力', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '挑战一天不看社交媒体', desc: '摆脱信息焦虑，回归现实', mood: '充实', cost: '1天' },
  { series_id: 'A', title: '自制一杯特调饮品', desc: '享受动手DIY的乐趣', mood: '治愈', cost: '20分钟' },
  { series_id: 'A', title: '整理电脑桌面文件', desc: '整理环境，理顺心情', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '跟着教程画一幅数字油画', desc: '沉浸绘画，体验心流', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '给自己做一次手部护理', desc: '细致呵护自己，提升幸福感', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '研究星座或MBTI性格分析', desc: '探索自我，了解他人', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '整理手机相册、删除废片', desc: '释出内存，回顾美好', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '尝试做家庭版烧烤', desc: '在家也能享受美食快乐', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '学习基础刺绣', desc: '静心专注，创造指尖艺术', mood: '宁静', cost: '2小时' },
  { series_id: 'A', title: '给绿植修剪枝叶、换盆', desc: '照顾植物，感受生命力量', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '练习书法或英文花体字', desc: '练字静心，提升气质', mood: '宁静', cost: '1小时' },
  { series_id: 'A', title: '给未来的自己写一封信', desc: '与内心对话，记录当下', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '尝试冥想10分钟', desc: '缓解焦虑，放松身心', mood: '宁静', cost: '10分钟' },
  { series_id: 'A', title: '整理云端存储空间', desc: '数字极简，减轻负担', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '学折纸或剪纸艺术', desc: '感受传统文化与手工乐趣', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '挑战一天喝够2升水', desc: '促进新陈代谢，健康生活', mood: '充实', cost: '1天' },
  { series_id: 'A', title: '做一个手工香薰蜡烛', desc: '点亮生活，愉悦心情', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '尝试写一首小诗', desc: '发挥文字创造力，表达情感', mood: '宁静', cost: '30分钟' },
  { series_id: 'A', title: '学习用毛线织杯垫', desc: '温暖手工，耐心养成', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '泡一壶花果茶，慢慢喝完', desc: '放慢节奏，感受生活', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '研究茶叶的种类和冲泡', desc: '品味茶文化，提升生活格调', mood: '宁静', cost: '1小时' },
  { series_id: 'A', title: '整理药箱，补充常备药', desc: '有备无患，守护家人健康', mood: '充实', cost: '30分钟' },
  { series_id: 'A', title: '用手机拍一组家居静物照片', desc: '发现生活之美，练习摄影', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '尝试用旧衣服改造一件新物', desc: '旧物改造，环保又创意', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '睡前写成功日记（记3件好事）', desc: '培养感恩心态，积极生活', mood: '治愈', cost: '10分钟' },
  { series_id: 'A', title: '录制一段ASMR声音', desc: '探索声音的奥秘，自我放松', mood: '放松', cost: '20分钟' },
  { series_id: 'A', title: '跟着视频学一支简单的舞蹈', desc: '活动身体，快乐起舞', mood: '充满活力', cost: '30分钟' },
  { series_id: 'A', title: '给房间来一次彻底断舍离', desc: '舍弃杂物，清爽身心', mood: '充实', cost: '3小时' },
  { series_id: 'A', title: '学做一道异国甜点', desc: '体验异国风味，享受烘焙', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '整理书架，按颜色分类', desc: '视觉疗愈，找书更方便', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '尝试做家庭版SPA', desc: '在家享受舒适的放松时光', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '学习几个手语动作', desc: '拓展沟通技能，感受无声之美', mood: '专注', cost: '30分钟' },
  { series_id: 'A', title: '自制水果冰棍', desc: '健康解暑，夏日必备', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '模仿一部电影的经典片段', desc: '趣味自娱，释放表演欲', mood: '开心', cost: '30分钟' },
  { series_id: 'A', title: '研究家居风水小知识', desc: '改善居住环境，提升运气', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '录一段自己的声音日记', desc: '记录心情，回顾成长', mood: '治愈', cost: '15分钟' },
  { series_id: 'A', title: '清洁保养皮具和鞋子', desc: '爱护物品，延长使用寿命', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '写下100件想感恩的事', desc: '培养感恩心态，提升幸福感', mood: '治愈', cost: '30分钟' },
  { series_id: 'A', title: '学习一个魔术技巧', desc: '增加社交互动的小乐趣', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '给家具换一个摆放位置', desc: '改变空间布局，带来新鲜感', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '逛夜市，吃遍小吃摊', desc: '感受城市烟火气，大饱口福', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '去美术馆或博物馆看新展', desc: '接受艺术熏陶，提升审美', mood: '充实', cost: '半天' },
  { series_id: 'A', title: '打卡网红建筑拍照', desc: '探索城市新地标，记录生活', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '参加城市解谜闯关活动', desc: '烧脑又刺激，感受团队合作', mood: '充满活力', cost: '半天' },
  { series_id: 'A', title: '坐绿皮火车去附近小镇', desc: '慢节奏旅行，体验别样风情', mood: '治愈', cost: '1天' },
  { series_id: 'A', title: '去花市买一束鲜花', desc: '装点生活，提升幸福感', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '探访古建筑或历史遗址', desc: '触摸历史，感受文化底蕴', mood: '充实', cost: '半天' },
  { series_id: 'A', title: '体验房车露营', desc: '亲近自然，享受户外生活', mood: '充满活力', cost: '1天' },
  { series_id: 'A', title: '去剧院看一场话剧', desc: '感受舞台魅力，沉浸艺术', mood: '充实', cost: '夜晚' },
  { series_id: 'A', title: '参加读书会或分享沙龙', desc: '思想碰撞，结交同好', mood: '充实', cost: '2小时' },
  { series_id: 'A', title: '去海边或湖边捡石头/贝壳', desc: '寻找自然宝藏，治愈心灵', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '坐公交车随机一站下车', desc: '城市盲盒，探索未知角落', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '去水族馆或动物园', desc: '与动物互动，回归童真', mood: '开心', cost: '半天' },
  { series_id: 'A', title: '体验陶艺或油画课', desc: '动手创作，培养艺术细胞', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '逛旧货市场或跳蚤市场', desc: '淘宝贝，体验市井生活', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '参加户外瑜伽或冥想活动', desc: '在自然中放松身心', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '去露天影院看电影', desc: '星空下的浪漫观影体验', mood: '治愈', cost: '夜晚' },
  { series_id: 'A', title: '探索一条从未走过的小巷', desc: '发现城市隐藏的惊喜', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '体验室内滑雪或滑冰', desc: '刺激好玩，挑战自我', mood: '充满活力', cost: '2小时' },
  { series_id: 'A', title: '去温泉或spa馆放松', desc: '舒缓疲劳，享受惬意时光', mood: '放松', cost: '半天' },
  { series_id: 'A', title: '参加文化节或市集', desc: '感受多元文化，融入当地', mood: '开心', cost: '半天' },
  { series_id: 'A', title: '去琴行体验不同乐器', desc: '发掘音乐兴趣，培养爱好', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '去公园划船', desc: '泛舟湖上，享受悠闲时光', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '参观本地的手工作坊', desc: '了解传统手艺，感受匠心', mood: '充实', cost: '2小时' },
  { series_id: 'A', title: '体验植物染色或皮具制作', desc: '亲手制作独一无二的作品', mood: '开心', cost: '2小时' },
  { series_id: 'A', title: '去现场看体育比赛', desc: '感受竞技热血，尽情呐喊', mood: '充满活力', cost: '半天' },
  { series_id: 'A', title: '逛特色超市（如进口超市）', desc: '发现新奇商品，满足好奇心', mood: '开心', cost: '1小时' },
  { series_id: 'A', title: '去最近的山上看日出日落', desc: '感受自然壮美，治愈心灵', mood: '治愈', cost: '半天' },
  { series_id: 'A', title: '参加烘焙或咖啡课程', desc: '学习新技能，享受美食', mood: '充实', cost: '2小时' },
  { series_id: 'A', title: '探索城市废墟（注意安全）', desc: '废墟美学，感受历史痕迹', mood: '专注', cost: '2小时' },
  { series_id: 'A', title: '体验射箭或攀岩体验课', desc: '挑战体能，释放压力', mood: '充满活力', cost: '2小时' },
  { series_id: 'A', title: '找一片草坪躺下看云', desc: '放空大脑，享受宁静', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '去迪士尼或游乐场玩', desc: '找回童心，尽情快乐', mood: '开心', cost: '1天' },
  { series_id: 'A', title: '参加志愿者活动', desc: '奉献爱心，收获感动', mood: '充实', cost: '半天' },
  { series_id: 'A', title: '坐轮渡或观光巴士看城市', desc: '换个视角看熟悉的地方', mood: '治愈', cost: '1小时' },
  { series_id: 'A', title: '去天文馆看星空投影', desc: '体验宇宙浩瀚，浪漫唯美', mood: '治愈', cost: '2小时' },
  { series_id: 'A', title: '体验卡丁车或碰碰车', desc: '速度与激情，释放压力', mood: '充满活力', cost: '1小时' },
  { series_id: 'A', title: '去郊外采摘当季水果', desc: '亲近自然，享受丰收喜悦', mood: '开心', cost: '半天' },
  { series_id: 'A', title: '逛独立设计品牌店', desc: '发现小众好物，提升品味', mood: '充实', cost: '1小时' },
  { series_id: 'A', title: '体验潜水或浮潜（室内也可）', desc: '探索水下世界，奇妙体验', mood: '充满活力', cost: '半天' },
  // 系列 B：改变人生的1000个传记
  { series_id: 'B', title: '褚时健：从烟王到橙王', desc: '永不放弃', mood: '励志', cost: '15分钟' },
  { series_id: 'B', title: '玛丽·居里：两获诺奖', desc: '女性力量', mood: '励志', cost: '15分钟' },
  { series_id: 'B', title: '林肯：从失落到总统', desc: '坚韧不拔', mood: '励志', cost: '15分钟' },
  { series_id: 'B', title: '乔布斯：Stay Hungry', desc: '改变世界', mood: '搞钱', cost: '15分钟' },
  { series_id: 'B', title: '莫扎特：音乐神童', desc: '天才之路', mood: '文艺', cost: '15分钟' },
  { series_id: 'B', title: '甘地：非暴力抗争', desc: '和平力量', mood: '深思', cost: '15分钟' },
  { series_id: 'B', title: 'JK罗琳：从失业到富豪', desc: '坚持梦想', mood: '搞钱', cost: '15分钟' },
  { series_id: 'B', title: '埃隆·马斯克：疯狂梦想家', desc: '未来视角', mood: '搞钱', cost: '15分钟' },
  { series_id: 'B', title: '海伦·凯勒：假如给我三天光明', desc: '生命奇迹', mood: '励志', cost: '15分钟' },
  { series_id: 'B', title: '达芬奇：跨界天才', desc: '好奇心', mood: '文艺', cost: '15分钟' },
  // 系列 C：从0到1的1000个创业经
  { series_id: 'C', title: '摆摊卖手冲咖啡', desc: '低成本创业', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '小红书宠物博主', desc: '内容变现', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '家庭烘焙私房', desc: '美食创业', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '二手书循环商店', desc: '环保创业', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '线上健身教练', desc: '知识付费', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '自制手工皂售卖', desc: '手工创业', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '社区团购团长', desc: '社群经济', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '摄影约拍', desc: '技能变现', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '课程分销', desc: '副业项目', mood: '搞钱', cost: '10分钟' },
  { series_id: 'C', title: '公众号流量主', desc: '文字变现', mood: '搞钱', cost: '10分钟' },
  // 系列 D：看完格局打开的1000部电影
  { series_id: 'D', title: '肖申克的救赎', desc: '希望与自由', mood: '深思', cost: '2小时' },
  { series_id: 'D', title: '教父', desc: '家族与权力', mood: '搞钱', cost: '2.5小时' },
  { series_id: 'D', title: '阿甘正传', desc: '傻人有傻福', mood: '治愈', cost: '2小时' },
  { series_id: 'D', title: '霸王别姬', desc: '时代悲歌', mood: '深思', cost: '2.5小时' },
  { series_id: 'D', title: '盗梦空间', desc: '梦境与现实', mood: '搞钱', cost: '2小时' },
  { series_id: 'D', title: '星际穿越', desc: '爱与时间', mood: '深思', cost: '2.5小时' },
  { series_id: 'D', title: '美丽人生', desc: '父爱如山', mood: '治愈', cost: '2小时' },
  { series_id: 'D', title: '这个杀手不太冷', desc: '温暖救赎', mood: '治愈', cost: '1.5小时' },
  { series_id: 'D', title: '海上钢琴师', desc: '孤独与选择', mood: '文艺', cost: '2小时' },
  { series_id: 'D', title: '三傻大闹宝莱坞', desc: '教育反思', mood: '启发', cost: '2.5小时' },
  // 系列 E：值得反复读的1000本书
  { series_id: 'E', title: '活着', desc: '生命的坚韧', mood: '深思', cost: '3小时' },
  { series_id: 'E', title: '小王子', desc: '纯真与爱', mood: '治愈', cost: '1小时' },
  { series_id: 'E', title: '百年孤独', desc: '魔幻现实', mood: '文艺', cost: '5小时' },
  { series_id: 'E', title: '人类简史', desc: '认知革命', mood: '搞钱', cost: '4小时' },
  { series_id: 'E', title: '学会提问', desc: '批判思维', mood: '搞钱', cost: '2小时' },
  { series_id: 'E', title: '解忧杂货店', desc: '温情推理', mood: '治愈', cost: '2小时' },
  { series_id: 'E', title: '追风筝的人', desc: '救赎与友谊', mood: '深思', cost: '3小时' },
  { series_id: 'E', title: '乌合之众', desc: '大众心理', mood: '搞钱', cost: '2小时' },
  { series_id: 'E', title: '平凡的世界', desc: '奋斗人生', mood: '励志', cost: '6小时' },
  { series_id: 'E', title: '瓦尔登湖', desc: '极简生活', mood: '治愈', cost: '3小时' },
  // 系列 F：吃遍全国的1000道家常菜
  { series_id: 'F', title: '番茄炒蛋', desc: '国民第一菜', mood: '温暖', cost: '15分钟' },
  { series_id: 'F', title: '红烧肉', desc: '妈妈的味道', mood: '温暖', cost: '1小时' },
  { series_id: 'F', title: '鱼香肉丝', desc: '酸甜辣', mood: '治愈', cost: '25分钟' },
  { series_id: 'F', title: '水煮鱼', desc: '麻辣鲜香', mood: '解压', cost: '30分钟' },
  { series_id: 'F', title: '宫保鸡丁', desc: '经典川菜', mood: '治愈', cost: '20分钟' },
  { series_id: 'F', title: '酸辣土豆丝', desc: '快手家常', mood: '温暖', cost: '10分钟' },
  { series_id: 'F', title: '糖醋排骨', desc: '酸甜可口', mood: '温暖', cost: '40分钟' },
  { series_id: 'F', title: '蒜蓉西兰花', desc: '健康素食', mood: '治愈', cost: '10分钟' },
  { series_id: 'F', title: '麻婆豆腐', desc: '下饭神器', mood: '解压', cost: '15分钟' },
  { series_id: 'F', title: '清蒸鲈鱼', desc: '原汁原味', mood: '温暖', cost: '20分钟' },
  // 系列 G：1000个极简生活妙招
  { series_id: 'G', title: '用旧报纸擦玻璃', desc: '废物利用', mood: '清爽', cost: '5分钟' },
  { series_id: 'G', title: '一物多用：小苏打', desc: '清洁万能', mood: '搞钱', cost: '5分钟' },
  { series_id: 'G', title: '衣架变手机支架', desc: 'DIY', mood: '专注', cost: '2分钟' },
  { series_id: 'G', title: '冰箱除味用柠檬', desc: '天然除味', mood: '清爽', cost: '3分钟' },
  { series_id: 'G', title: '旧T恤做购物袋', desc: '环保', mood: '清爽', cost: '10分钟' },
  { series_id: 'G', title: '用咖啡渣做肥料', desc: '养花妙招', mood: '治愈', cost: '5分钟' },
  { series_id: 'G', title: '抽屉收纳用分隔板', desc: '整齐', mood: '清爽', cost: '15分钟' },
  { series_id: 'G', title: '白醋去除水垢', desc: '清洁', mood: '清爽', cost: '10分钟' },
  { series_id: 'G', title: '自制香薰蜡烛', desc: '仪式感', mood: '治愈', cost: '20分钟' },
  { series_id: 'G', title: '旧书变装饰品', desc: '文艺', mood: '文艺', cost: '10分钟' },
  // 系列 H：1000个周末去哪儿
  { series_id: 'H', title: '本地植物园', desc: '亲近自然', mood: '治愈', cost: '半天' },
  { series_id: 'H', title: '城市美术馆', desc: '艺术熏陶', mood: '文艺', cost: '半天' },
  { series_id: 'H', title: '近郊露营地', desc: '星空夜色', mood: '治愈', cost: '1天' },
  { series_id: 'H', title: '古镇一日游', desc: '穿越时光', mood: '文艺', cost: '1天' },
  { series_id: 'H', title: '海洋馆', desc: '蓝色世界', mood: '治愈', cost: '半天' },
  { series_id: 'H', title: '博物馆', desc: '了解历史', mood: '搞钱', cost: '半天' },
  { series_id: 'H', title: '登山徒步', desc: '挑战自我', mood: '励志', cost: '1天' },
  { series_id: 'H', title: '湖边骑行', desc: '微风拂面', mood: '治愈', cost: '半天' },
  { series_id: 'H', title: '农场采摘', desc: '田园之乐', mood: '温暖', cost: '半天' },
  { series_id: 'H', title: '胡同Citywalk', desc: '城市探索', mood: '文艺', cost: '半天' },
  // 系列 I：1000个治愈内耗的瞬间
  { series_id: 'I', title: '听雨声白噪音', desc: '静心', mood: '治愈', cost: '5分钟' },
  { series_id: 'I', title: '看云朵变化', desc: '放空', mood: '治愈', cost: '10分钟' },
  { series_id: 'I', title: '深呼吸冥想', desc: '减压', mood: '治愈', cost: '5分钟' },
  { series_id: 'I', title: '写感恩日记', desc: '积极心态', mood: '治愈', cost: '10分钟' },
  { series_id: 'I', title: '泡一杯热茶', desc: '温暖自己', mood: '治愈', cost: '5分钟' },
  { series_id: 'I', title: '抱抱大树', desc: '接地气', mood: '治愈', cost: '3分钟' },
  { series_id: 'I', title: '画一幅涂鸦', desc: '释放情绪', mood: '治愈', cost: '15分钟' },
  { series_id: 'I', title: '听一首老歌', desc: '回忆美好', mood: '治愈', cost: '3分钟' },
  { series_id: 'I', title: '仰望星空', desc: '渺小与伟大', mood: '治愈', cost: '10分钟' },
  { series_id: 'I', title: '和宠物玩耍', desc: '无条件爱', mood: '治愈', cost: '10分钟' },
  // 系列 J：1000个搞钱/省钱冷知识
  { series_id: 'J', title: '信用卡积分换里程', desc: '省钱', mood: '搞钱', cost: '2分钟' },
  { series_id: 'J', title: '超市晚间折扣时段', desc: '省钱', mood: '搞钱', cost: '1分钟' },
  { series_id: 'J', title: '二手平台出闲置', desc: '变现', mood: '搞钱', cost: '10分钟' },
  { series_id: 'J', title: '团购优惠券叠加', desc: '省钱', mood: '搞钱', cost: '2分钟' },
  { series_id: 'J', title: '基金定投策略', desc: '理财', mood: '搞钱', cost: '10分钟' },
  { series_id: 'J', title: '话费套餐优化', desc: '省钱', mood: '搞钱', cost: '5分钟' },
  { series_id: 'J', title: '顺风车乘客', desc: '副业', mood: '搞钱', cost: '5分钟' },
  { series_id: 'J', title: '问卷调查赚积分', desc: '小钱', mood: '搞钱', cost: '10分钟' },
  { series_id: 'J', title: '用购物返利APP', desc: '省钱', mood: '搞钱', cost: '2分钟' },
  { series_id: 'J', title: '早起抢优惠券', desc: '省钱', mood: '搞钱', cost: '5分钟' }
];

// ======================= 新增书籍数据（147 本） =======================
const BOOKS_RAW = [
  // ========== 文学 ==========
  { t: '百年孤独', a: '加西亚·马尔克斯', r: '9.3', p: '1967年', g: '文学', s: '魔幻现实主义巅峰之作，讲述了布恩迪亚家族七代人的传奇故事，马孔多小镇的兴衰史映射了整个拉美大陆的百年变迁。' },
  { t: '三体', a: '刘慈欣', r: '8.9', p: '2008年', g: '文学', s: '中国科幻文学的里程碑之作，从文革时期的红岸基地出发，揭示了宇宙文明间的黑暗森林法则。' },
  { t: '围城', a: '钱钟书', r: '9.0', p: '1947年', g: '文学', s: '一部充满智慧与幽默的讽刺杰作，深刻揭示了现代知识分子的精神困境。' },
  { t: '边城', a: '沈从文', r: '8.7', p: '1934年', g: '文学', s: '中国现代文学中最纯净的田园牧歌，湘西茶峒小镇上少女翠翠的爱情故事。' },
  { t: '白鹿原', a: '陈忠实', r: '9.2', p: '1993年', g: '文学', s: '渭河平原上白、鹿两家的恩怨纠葛，浓缩了中国近现代半个多世纪的历史变迁。' },
  { t: '尘埃落定', a: '阿来', r: '8.9', p: '1998年', g: '文学', s: '通过土司家族"傻子"少爷的视角，讲述了藏族土司制度的兴衰与消亡。' },
  { t: '黄金时代', a: '王小波', r: '8.9', p: '1994年', g: '文学', s: '以知青岁月为背景，展现了荒诞年代里对自由与真实的执着追求。' },
  { t: '白夜行', a: '东野圭吾', r: '9.2', p: '1999年', g: '文学', s: '东野圭吾的巅峰之作，一段令人窒息的爱与罪。' },
  { t: '嫌疑人X的献身', a: '东野圭吾', r: '9.0', p: '2005年', g: '文学', s: '将爱情与推理完美融合，最纯粹的爱可以让人献出一切。' },
  { t: '1984', a: '乔治·奥威尔', r: '9.4', p: '1949年', g: '文学', s: '反乌托邦文学的经典之作，对权力、真理与自由的思考至今仍有强烈的现实意义。' },
  { t: '动物农场', a: '乔治·奥威尔', r: '9.3', p: '1945年', g: '文学', s: '一部用动物寓言写成的政治讽刺经典。' },
  { t: '局外人', a: '加缪', r: '9.1', p: '1942年', g: '文学', s: '存在主义文学的奠基之作，揭示了社会对"不合规矩"之人的排斥与审判。' },
  { t: '鼠疫', a: '加缪', r: '8.9', p: '1947年', g: '文学', s: '一部关于疫情下人性与反抗的哲理小说。' },
  { t: '灿烂千阳', a: '卡勒德·胡赛尼', r: '8.8', p: '2007年', g: '文学', s: '通过阿富汗两位女性的故事，展现了战争阴影下女性的苦难与坚韧。' },
  { t: '挪威的森林', a: '村上春树', r: '8.7', p: '1987年', g: '文学', s: '村上春树最畅销的纯爱小说，一段关于青春、爱情与死亡的忧伤记忆。' },
  { t: '海边的卡夫卡', a: '村上春树', r: '8.5', p: '2002年', g: '文学', s: '一部充满隐喻与奇幻色彩的成长小说。' },
  { t: '魔戒', a: '托尔金', r: '9.0', p: '1954年', g: '文学', s: '现代奇幻文学的奠基之作。' },
  { t: '傲慢与偏见', a: '简·奥斯汀', r: '9.0', p: '1813年', g: '文学', s: '英国文学史上最受欢迎的爱情小说之一。' },
  { t: '简爱', a: '夏洛蒂·勃朗特', r: '8.7', p: '1847年', g: '文学', s: '一部追求女性独立与尊严的经典之作。' },
  { t: '呼啸山庄', a: '艾米莉·勃朗特', r: '8.8', p: '1847年', g: '文学', s: '一部充满暴力与激情的哥特式爱情悲剧。' },
  { t: '悲惨世界', a: '雨果', r: '9.1', p: '1862年', g: '文学', s: '法国文学史上最宏大的社会画卷之一。' },
  { t: '战争与和平', a: '托尔斯泰', r: '9.5', p: '1869年', g: '文学', s: '文学史上最伟大的小说之一。' },
  { t: '安娜·卡列尼娜', a: '托尔斯泰', r: '9.3', p: '1877年', g: '文学', s: '探讨爱情、婚姻与社会道德的巨著。' },
  { t: '罪与罚', a: '陀思妥耶夫斯基', r: '9.2', p: '1866年', g: '文学', s: '深入探讨人性、罪恶与救赎的心理小说巅峰。' },
  { t: '卡拉马佐夫兄弟', a: '陀思妥耶夫斯基', r: '9.4', p: '1880年', g: '文学', s: '陀思妥耶夫斯基最后的巅峰之作。' },
  { t: '大师与玛格丽特', a: '布尔加科夫', r: '9.1', p: '1967年', g: '文学', s: '将魔幻与现实完美融合的讽刺杰作。' },
  { t: '红与黑', a: '司汤达', r: '8.9', p: '1830年', g: '文学', s: '法国现实主义文学的开山之作。' },
  { t: '飘', a: '玛格丽特·米切尔', r: '9.3', p: '1936年', g: '文学', s: '美国文学史上最受欢迎的小说之一。' },
  { t: '老人与海', a: '海明威', r: '8.5', p: '1952年', g: '文学', s: '海明威最具代表性的作品，展现了人类不屈不挠的精神力量。' },
  { t: '基督山伯爵', a: '大仲马', r: '9.0', p: '1844年', g: '文学', s: '一部关于复仇与正义的经典通俗小说。' },
  { t: '骆驼祥子', a: '老舍', r: '8.8', p: '1936年', g: '文学', s: '北平车夫祥子三次买车三次失去的悲剧人生。' },
  { t: '四世同堂', a: '老舍', r: '8.9', p: '1949年', g: '文学', s: '一部描写抗战时期北平市民生活的长篇巨著。' },
  { t: '寒夜', a: '巴金', r: '8.1', p: '1947年', g: '文学', s: '巴金最后的长篇小说，也是一部深刻的社会悲剧。' },
  { t: '家', a: '巴金', r: '8.4', p: '1931年', g: '文学', s: '巴金代表作《激流三部曲》之首。' },
  { t: '呐喊', a: '鲁迅', r: '9.2', p: '1923年', g: '文学', s: '中国现代小说的奠基之作。' },
  { t: '彷徨', a: '鲁迅', r: '8.9', p: '1926年', g: '文学', s: '鲁迅第二部小说集。' },
  { t: '天龙八部', a: '金庸', r: '9.2', p: '1963年', g: '文学', s: '金庸武侠巅峰之作。' },
  { t: '射雕英雄传', a: '金庸', r: '9.0', p: '1957年', g: '文学', s: '金庸武侠经典，郭靖黄蓉的爱情与成长。' },

  // ========== 科幻 ==========
  { t: '三体2：黑暗森林', a: '刘慈欣', r: '9.3', p: '2008年', g: '科幻', s: '提出了震撼人心的"黑暗森林"宇宙社会学理论。' },
  { t: '三体3：死神永生', a: '刘慈欣', r: '9.2', p: '2010年', g: '科幻', s: '将科幻文学的格局推向了前所未有的高度。' },
  { t: '球状闪电', a: '刘慈欣', r: '8.5', p: '2005年', g: '科幻', s: '刘慈欣的早期科幻杰作。' },
  { t: '流浪地球', a: '刘慈欣', r: '8.6', p: '2000年', g: '科幻', s: '人类带着地球一起逃离太阳系，踏上星际流浪。' },
  { t: '银河帝国：基地', a: '艾萨克·阿西莫夫', r: '9.1', p: '1951年', g: '科幻', s: '心理史学家谢顿预见了银河帝国的衰亡。' },
  { t: '沙丘', a: '弗兰克·赫伯特', r: '8.7', p: '1965年', g: '科幻', s: '科幻史上的里程碑之作，宏大的宇宙史诗。' },
  { t: '海伯利安', a: '丹·西蒙斯', r: '8.8', p: '1989年', g: '科幻', s: '一部融合了诗歌、宗教与硬核科幻的巨著。' },
  { t: '安德的游戏', a: '奥森·斯科特·卡德', r: '8.7', p: '1985年', g: '科幻', s: '天才少年安德的成长故事。' },
  { t: '沙丘救世主', a: '弗兰克·赫伯特', r: '8.2', p: '1969年', g: '科幻', s: '《沙丘》续集，保罗·厄崔迪成为皇帝后面临的危机。' },
  { t: '沙丘之子', a: '弗兰克·赫伯特', r: '8.3', p: '1976年', g: '科幻', s: '沙丘系列第三部。' },
  { t: '基地与帝国', a: '艾萨克·阿西莫夫', r: '8.8', p: '1952年', g: '科幻', s: '基地系列第二部。' },
  { t: '第二基地', a: '艾萨克·阿西莫夫', r: '8.9', p: '1953年', g: '科幻', s: '基地三部曲终结篇。' },
  { t: '银河系搭车客指南', a: '道格拉斯·亚当斯', r: '8.6', p: '1979年', g: '科幻', s: '一部充满英式幽默的科幻喜剧。' },
  { t: '神经漫游者', a: '威廉·吉布森', r: '8.4', p: '1984年', g: '科幻', s: '赛博朋克流派的奠基之作。' },
  { t: '仿生人会梦见电子羊吗？', a: '菲利普·迪克', r: '8.3', p: '1968年', g: '科幻', s: '《银翼杀手》的原著小说。' },
  { t: '尤比克', a: '菲利普·迪克', r: '8.1', p: '1969年', g: '科幻', s: '在死亡与冷冻复苏的未来世界中，现实与幻觉交织。' },
  { t: '高堡奇人', a: '菲利普·迪克', r: '8.2', p: '1962年', g: '科幻', s: '假设轴心国赢得二战。' },
  { t: '时间机器', a: 'H.G.威尔斯', r: '8.2', p: '1895年', g: '科幻', s: '科幻文学的经典开山之作。' },
  { t: '世界大战', a: 'H.G.威尔斯', r: '8.1', p: '1898年', g: '科幻', s: '火星人入侵地球的经典故事。' },
  { t: '童年的终结', a: '阿瑟·克拉克', r: '8.3', p: '1953年', g: '科幻', s: '外星人降临地球帮助人类实现和平。' },

  // ========== 历史 ==========
  { t: '史记', a: '司马迁', r: '9.2', p: '公元前1世纪', g: '历史', s: '中国历史上最伟大的史学著作。' },
  { t: '资治通鉴', a: '司马光', r: '9.0', p: '1084年', g: '历史', s: '中国历史上规模最大的编年体通史。' },
  { t: '未来简史', a: '尤瓦尔·赫拉利', r: '8.4', p: '2015年', g: '历史', s: '探讨了在21世纪，人类将如何追求"永生、幸福、神性"。' },
  { t: '枪炮、病菌与钢铁', a: '贾雷德·戴蒙德', r: '8.9', p: '1997年', g: '历史', s: '一部解释人类社会发展不平等根源的宏大著作。' },
  { t: '万历十五年', a: '黄仁宇', r: '8.5', p: '1982年', g: '历史', s: '一部改变中国人历史观的名著。' },
  { t: '中国大历史', a: '黄仁宇', r: '8.0', p: '1991年', g: '历史', s: '以宏观的视野审视中国历史。' },
  { t: '全球通史', a: '斯塔夫里阿诺斯', r: '8.7', p: '1970年', g: '历史', s: '一部打破欧洲中心论的世界史经典。' },
  { t: '中国近代史', a: '蒋廷黻', r: '8.6', p: '1938年', g: '历史', s: '一部简洁而深刻的近代史著作。' },
  { t: '剑桥中国史', a: '费正清等', r: '8.8', p: '1978年', g: '历史', s: '西方学术界最具权威的中国通史之一。' },
  { t: '丝绸之路', a: '彼得·弗兰科潘', r: '8.2', p: '2015年', g: '历史', s: '一部从全球视角重新解读世界史的著作。' },
  { t: '大国的兴衰', a: '保罗·肯尼迪', r: '8.1', p: '1987年', g: '历史', s: '一部关于国际政治经济格局的经典之作。' },
  { t: '罗马帝国衰亡史', a: '爱德华·吉本', r: '8.7', p: '1776年', g: '历史', s: '西方史学史上的不朽巨著。' },
  { t: '法国大革命讲稿', a: '阿克顿勋爵', r: '8.0', p: '1900年', g: '历史', s: '深入分析了法国大革命的起因、过程及其影响。' },
  { t: '历史研究', a: '汤因比', r: '8.3', p: '1934年', g: '历史', s: '汤因比文明史观的代表作。' },
  { t: '叫魂', a: '孔飞力', r: '8.9', p: '1990年', g: '历史', s: '以1768年叫魂妖术大恐慌为切入点。' },

  // ========== 经济 ==========
  { t: '穷查理宝典', a: '查理·芒格', r: '8.9', p: '2005年', g: '经济', s: '投资大师查理·芒格智慧箴言的集大成之作。' },
  { t: '聪明的投资者', a: '本杰明·格雷厄姆', r: '8.8', p: '1949年', g: '经济', s: '价值投资的开山之作。' },
  { t: '国富论', a: '亚当·斯密', r: '8.5', p: '1776年', g: '经济', s: '现代经济学的奠基之作。' },
  { t: '经济学原理', a: '曼昆', r: '8.4', p: '1998年', g: '经济', s: '全球最受欢迎的经济学入门教材。' },
  { t: '黑天鹅', a: '纳西姆·塔勒布', r: '8.2', p: '2007年', g: '经济', s: '一部关于不确定性、风险与随机性的经典著作。' },
  { t: '反脆弱', a: '纳西姆·塔勒布', r: '8.1', p: '2012年', g: '经济', s: '提出了"反脆弱"这一全新概念。' },
  { t: '原则', a: '瑞·达利欧', r: '8.4', p: '2017年', g: '经济', s: '桥水基金创始人瑞·达利欧的人生与工作原则总结。' },
  { t: '创新者的窘境', a: '克莱顿·克里斯坦森', r: '8.6', p: '1997年', g: '经济', s: '提出了"颠覆性创新"理论。' },
  { t: '从优秀到卓越', a: '吉姆·柯林斯', r: '8.3', p: '2001年', g: '经济', s: '总结了从"优秀"到"卓越"的关键要素。' },
  { t: '高效能人士的七个习惯', a: '史蒂芬·柯维', r: '8.6', p: '1989年', g: '经济', s: '一部影响无数人的个人成长经典。' },
  { t: '影响力', a: '罗伯特·西奥迪尼', r: '8.6', p: '1984年', g: '经济', s: '揭示了六大影响力原则。' },
  { t: '思考，快与慢', a: '丹尼尔·卡尼曼', r: '8.5', p: '2011年', g: '经济', s: '诺贝尔经济学奖得主卡尼曼的代表作。' },
  { t: '穷爸爸富爸爸', a: '罗伯特·清崎', r: '8.2', p: '1997年', g: '经济', s: '一部改变无数人理财观念的畅销书。' },
  { t: '小狗钱钱', a: '博多·舍费尔', r: '8.6', p: '1999年', g: '经济', s: '一本写给儿童的理财启蒙书。' },
  { t: '投资中最简单的事', a: '邱国鹭', r: '8.4', p: '2014年', g: '经济', s: '中国知名基金经理邱国鹭的投资心得。' },

  // ========== 哲学 ==========
  { t: '西方哲学史', a: '罗素', r: '8.5', p: '1945年', g: '哲学', s: '诺贝尔文学奖得主罗素的哲学史经典。' },
  { t: '中国哲学简史', a: '冯友兰', r: '8.8', p: '1948年', g: '哲学', s: '中国哲学入门的最佳选择。' },
  { t: '论语', a: '孔子', r: '9.1', p: '公元前5世纪', g: '哲学', s: '儒家思想的奠基之作。' },
  { t: '道德经', a: '老子', r: '9.2', p: '公元前4世纪', g: '哲学', s: '道家哲学的最高经典。' },
  { t: '庄子', a: '庄子', r: '9.0', p: '公元前4世纪', g: '哲学', s: '道家思想的瑰宝。' },
  { t: '理想国', a: '柏拉图', r: '9.0', p: '公元前4世纪', g: '哲学', s: '西方政治哲学的奠基之作。' },
  { t: '第二性', a: '西蒙·波伏娃', r: '8.8', p: '1949年', g: '哲学', s: '西方女性主义理论的奠基之作。' },
  { t: '规训与惩罚', a: '米歇尔·福柯', r: '8.6', p: '1975年', g: '哲学', s: '揭示了现代社会如何通过规训机制控制个体。' },
  { t: '疯癫与文明', a: '米歇尔·福柯', r: '8.4', p: '1961年', g: '哲学', s: '通过梳理西方社会对待疯癫的态度变迁。' },
  { t: '存在与时间', a: '海德格尔', r: '8.3', p: '1927年', g: '哲学', s: '20世纪最重要的哲学著作之一。' },
  { t: '纯粹理性批判', a: '康德', r: '8.4', p: '1781年', g: '哲学', s: '西方哲学史上最重要的著作之一。' },
  { t: '尼各马可伦理学', a: '亚里士多德', r: '8.6', p: '公元前4世纪', g: '哲学', s: '西方伦理学史上最重要的著作之一。' },
  { t: '沉默的大多数', a: '王小波', r: '8.9', p: '1997年', g: '哲学', s: '王小波最具影响力的杂文集。' },
  { t: '一只特立独行的猪', a: '王小波', r: '8.6', p: '1996年', g: '哲学', s: '王小波杂文的经典之作。' },
  { t: '人生的智慧', a: '叔本华', r: '8.3', p: '1851年', g: '哲学', s: '叔本华最受欢迎的著作。' },
  { t: '查拉图斯特拉如是说', a: '尼采', r: '8.3', p: '1885年', g: '哲学', s: '尼采最具代表性的哲学著作。' },
  { t: '权力意志', a: '尼采', r: '8.0', p: '1901年', g: '哲学', s: '尼采哲学思想的集大成之作。' },
  { t: '论自由', a: '约翰·密尔', r: '8.5', p: '1859年', g: '哲学', s: '西方自由主义理论的经典文献。' },
  { t: '社会契约论', a: '卢梭', r: '8.2', p: '1762年', g: '哲学', s: '"人生而自由，却无往不在枷锁之中"。' },
  { t: '给青年的十二封信', a: '朱光潜', r: '8.4', p: '1929年', g: '哲学', s: '美学大师朱光潜为青年读者写作的十二封书信。' },

  // ========== 艺术 ==========
  { t: '艺术的故事', a: '贡布里希', r: '9.2', p: '1950年', g: '艺术', s: '全球最畅销的艺术史入门读物。' },
  { t: '现代艺术150年', a: '威尔·贡培兹', r: '8.7', p: '2012年', g: '艺术', s: '一部让现代艺术变得容易理解的精彩读本。' },
  { t: '美的历程', a: '李泽厚', r: '8.8', p: '1981年', g: '艺术', s: '中国美学史上最具影响力的著作之一。' },
  { t: '美学散步', a: '宗白华', r: '8.5', p: '1981年', g: '艺术', s: '一部充满诗意的中国美学随笔。' },
  { t: '认识电影', a: '路易斯·贾内梯', r: '8.4', p: '1972年', g: '艺术', s: '全球最经典的电影入门教材。' },
  { t: '电影批评', a: '戴锦华', r: '8.0', p: '2004年', g: '艺术', s: '中国最具影响力的电影学者之一戴锦华的文集。' },
  { t: '艺术哲学', a: '丹纳', r: '8.3', p: '1869年', g: '艺术', s: '一部从社会学角度分析艺术的经典著作。' },
  { t: '罗丹艺术论', a: '罗丹', r: '8.1', p: '1900年', g: '艺术', s: '雕塑大师罗丹与作家葛赛尔的对话录。' },
  { t: '中国建筑史', a: '梁思成', r: '8.7', p: '1955年', g: '艺术', s: '中国建筑史研究的奠基之作。' },
  { t: '图像中国建筑史', a: '梁思成', r: '8.4', p: '1984年', g: '艺术', s: '用英文为中国古建筑"立传"的经典著作。' },
  { t: '书法有法', a: '孙晓云', r: '8.1', p: '2002年', g: '艺术', s: '一部关于中国书法鉴赏与学习的实用指南。' },
  { t: '写给大家的中国美术史', a: '蒋勋', r: '8.5', p: '1990年', g: '艺术', s: '蒋勋讲述中国美术发展史。' },
  { t: '写给大家的西方美术史', a: '蒋勋', r: '8.4', p: '2004年', g: '艺术', s: '系统介绍了西方美术的发展历程。' },
  { t: '听音乐', a: '罗杰·凯密恩', r: '8.3', p: '2011年', g: '艺术', s: '一部系统而通俗的音乐欣赏入门教材。' },
  { t: '古典音乐欣赏入门', a: '杨燕迪', r: '8.1', p: '2010年', g: '艺术', s: '为古典音乐入门者编写的指南。' },
  { t: '看电影的艺术', a: '约瑟夫·M·博格斯', r: '8.2', p: '2000年', g: '艺术', s: '一本系统介绍电影视听语言的教材。' },
  { t: '设计中的设计', a: '原研哉', r: '8.6', p: '2003年', g: '艺术', s: '"设计不是一种技能，而是感知世界的方式"。' },
  { t: '写给大家的设计书', a: '罗宾·威廉姆斯', r: '8.2', p: '1994年', g: '艺术', s: '一本经典的设计入门读物。' },
  { t: '艺术与视知觉', a: '阿恩海姆', r: '8.0', p: '1954年', g: '艺术', s: '一部从心理学角度分析视觉艺术的经典著作。' },

  // ========== 科普 ==========
  { t: '时间简史', a: '史蒂芬·霍金', r: '8.6', p: '1988年', g: '科普', s: '一部向大众普及宇宙学的科普经典。' },
  { t: '万物简史', a: '比尔·布莱森', r: '8.3', p: '2003年', g: '科普', s: '一部用幽默笔触书写的科学史。' },
  { t: '自私的基因', a: '理查德·道金斯', r: '8.5', p: '1976年', g: '科普', s: '道金斯提出了"自私的基因"理论。' },
  { t: '生命是什么', a: '薛定谔', r: '8.4', p: '1944年', g: '科普', s: '从物理学角度探讨生命的本质与遗传机制。' },
  { t: '双螺旋', a: '詹姆斯·沃森', r: '8.1', p: '1968年', g: '科普', s: 'DNA双螺旋结构发现者之一沃森的回忆录。' },
  { t: '数学之美', a: '吴军', r: '8.6', p: '2012年', g: '科普', s: '一部将数学与信息科学结合起来的科普佳作。' },
  { t: '浪潮之巅', a: '吴军', r: '8.5', p: '2011年', g: '科普', s: '一部关于IT产业历史的经典著作。' },
  { t: '全球科技通史', a: '吴军', r: '8.3', p: '2018年', g: '科普', s: '系统梳理了科技发展的全貌。' },
  { t: '智能时代', a: '吴军', r: '8.0', p: '2016年', g: '科普', s: '吴军对人工智能时代的系统思考。' },
  { t: '密码故事', a: '西蒙·辛格', r: '8.2', p: '1999年', g: '科普', s: '一部关于密码学历史的科普著作。' },
  { t: '上帝掷骰子吗', a: '曹天元', r: '8.6', p: '2006年', g: '科普', s: '一部关于量子力学的通俗科普读物。' },
  { t: '从一到无穷大', a: '乔治·伽莫夫', r: '8.4', p: '1947年', g: '科普', s: '一部经典的科普名著。' },
  { t: '宇宙简史', a: '史蒂芬·霍金', r: '8.2', p: '2005年', g: '科普', s: '霍金为普通读者撰写的宇宙学入门书。' },
  { t: '人类群星闪耀时', a: '斯蒂芬·茨威格', r: '8.7', p: '1927年', g: '科普', s: '选取了人类历史上十四个决定性的瞬间。' },
  { t: '寂静的春天', a: '蕾切尔·卡逊', r: '8.6', p: '1962年', g: '科普', s: '环境科学的奠基之作。' },
  { t: '物种起源', a: '达尔文', r: '8.7', p: '1859年', g: '科普', s: '进化论的奠基之作。' },
  { t: '人类宇宙', a: '布赖恩·考克斯', r: '8.0', p: '2011年', g: '科普', s: 'BBC纪录片同名书籍。' },
];

// ======================= 数据初始化 =======================
export async function onRequest(context) {
  const { env } = context;

  try {
    // 1. 建表（单行 SQL，避免 D1 多行解析问题）
    await env.DB.prepare(
      'CREATE TABLE IF NOT EXISTS content_library (id INTEGER PRIMARY KEY AUTOINCREMENT, series_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT, mood_tag TEXT, cost_time TEXT, pushed INTEGER DEFAULT 0, push_date TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)'
    ).run();

    // 2. 检查是否已有数据
    const count = await env.DB.prepare('SELECT COUNT(*) as total FROM content_library').first();
    if (count && count.total > 0) {
      return new Response(JSON.stringify({
        message: `✅ 数据已存在，共 ${count.total} 条，无需重复初始化`,
        count: count.total
      }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // 3. 构造原有 100 条数据
    const seedInsert = SEED_DATA.map(item => ({
      series_id: item.series_id,
      title: item.title,
      desc: item.desc,
      mood: item.mood,
      cost: item.cost,
      author: null,
      rating: null,
      publish_year: null,
      genre: null
    }));

    // 4. 构造书籍数据
    const bookInsert = BOOKS_RAW.map(b => ({
      series_id: 'E',
      title: b.t,
      desc: b.s,
      mood: b.g,
      cost: '📖 阅读',
      author: b.a,
      rating: b.r,
      publish_year: b.p,
      genre: b.g
    }));

    // 5. 过滤掉与原有系列 E 重复的书籍
    const originalE_Titles = new Set(
      SEED_DATA.filter(d => d.series_id === 'E').map(d => d.title)
    );
    const newBooks = bookInsert.filter(b => !originalE_Titles.has(b.title));

    // 6. 合并所有数据
    const ALL_DATA = [...seedInsert, ...newBooks];

    // 7. 批量插入
    const stmt = env.DB.prepare(
      'INSERT INTO content_library (series_id, title, description, mood_tag, cost_time, author, rating, publish_year, genre) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'
    );
    const batch = ALL_DATA.map(item =>
      stmt.bind(
        item.series_id,
        item.title,
        item.desc,
        item.mood,
        item.cost,
        item.author,
        item.rating,
        item.publish_year,
        item.genre
      )
    );
    await env.DB.batch(batch);

    return new Response(JSON.stringify({
      message: `✅ 数据初始化成功！原有 ${SEED_DATA.length} 条 + 新增书籍 ${newBooks.length} 本，共 ${ALL_DATA.length} 条`,
      originalCount: SEED_DATA.length,
      newBooksCount: newBooks.length,
      totalCount: ALL_DATA.length
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    return new Response(JSON.stringify({
      error: `❌ 初始化失败: ${error.message}`
    }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
